-- supabase/migrations/20260831120000_add_customer_history.sql
--
-- CORTE 1: Estructura de datos para clientes autenticados,
-- programa de puntos e historial permanente independiente
-- de las tablas operativas de pedidos.
--
-- NO modifica: init_schema.sql, orders, order_items, cron.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Extender loyalty_accounts con vínculo a Supabase Auth
-- ─────────────────────────────────────────────────────────────────────────────
-- Agrega user_id nullable; permite cuentas de lealtad legacy sin usuario auth.
-- ON DELETE SET NULL: si el usuario auth se elimina, la cuenta de puntos persiste.
ALTER TABLE public.loyalty_accounts
  ADD COLUMN IF NOT EXISTS user_id uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL;

-- Índice único parcial: no permite dos cuentas de lealtad para el mismo user_id,
-- pero permite múltiples filas con user_id NULL (cuentas legacy sin auth).
CREATE UNIQUE INDEX IF NOT EXISTS idx_loyalty_accounts_user_id
  ON public.loyalty_accounts(user_id)
  WHERE user_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Tabla de historial permanente de pedidos por cliente
-- ─────────────────────────────────────────────────────────────────────────────
-- DESACOPLADA de public.orders intencionalmente.
-- original_order_id guarda referencia informativa al pedido operativo,
-- pero NO tiene FOREIGN KEY hacia orders para que el historial sobreviva
-- cuando el cron elimine el registro operativo.
CREATE TABLE IF NOT EXISTS public.customer_order_history (
  id                  bigint generated by default as identity PRIMARY KEY,

  -- Referencia informativa al pedido operativo (sin FK, cron puede borrar orders)
  original_order_id   bigint NOT NULL,

  -- Vínculo al usuario autenticado (nullable: pedidos de kiosk anónimo sin cuenta)
  customer_id         uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Vínculo a la cuenta de lealtad (nullable: pedidos sin programa de puntos)
  loyalty_account_id  bigint NULL REFERENCES public.loyalty_accounts(id) ON DELETE SET NULL,

  -- Snapshot de datos del pedido al momento de pago
  order_number        int,
  order_date          date,
  type                text,
  customer_name       text,
  customer_phone      text,
  address_json        jsonb,

  -- Fotografía permanente de los ítems; desacoplada de order_items
  items_json          jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- Totales en centavos
  subtotal_cents      int NOT NULL DEFAULT 0,
  delivery_fee_cents  int NOT NULL DEFAULT 0,
  total_cents         int NOT NULL DEFAULT 0,

  -- Método de pago registrado en el momento del cobro
  payment_method      text,

  -- Puntos acreditados por este pedido
  points_earned       int NOT NULL DEFAULT 0,

  -- Marca temporal del pago (copiada de orders.paid_at al crear el snapshot)
  paid_at             timestamptz,

  created_at          timestamptz NOT NULL DEFAULT now(),

  -- Garantiza un único historial por pedido operativo
  CONSTRAINT customer_order_history_unique_order UNIQUE (original_order_id)
);

-- Índices para consultas frecuentes
CREATE INDEX IF NOT EXISTS idx_coh_customer_id
  ON public.customer_order_history(customer_id);

CREATE INDEX IF NOT EXISTS idx_coh_loyalty_account_id
  ON public.customer_order_history(loyalty_account_id);

CREATE INDEX IF NOT EXISTS idx_coh_created_at
  ON public.customer_order_history(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Extender loyalty_ledger con referencia al historial permanente
-- ─────────────────────────────────────────────────────────────────────────────
-- Mantiene order_id existente (no se elimina ni modifica).
-- Agrega order_history_id para vincular a customer_order_history.
-- ON DELETE SET NULL: si se borrara una entrada de historial, el movimiento persiste.
ALTER TABLE public.loyalty_ledger
  ADD COLUMN IF NOT EXISTS order_history_id bigint NULL
    REFERENCES public.customer_order_history(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_loyalty_ledger_order_history_id
  ON public.loyalty_ledger(order_history_id);

-- Índice único parcial de idempotencia:
-- como máximo un movimiento tipo 'earn' por entrada de historial.
-- Previene acreditación doble si un pedido se procesa más de una vez.
CREATE UNIQUE INDEX IF NOT EXISTS idx_loyalty_ledger_earn_per_history
  ON public.loyalty_ledger(order_history_id)
  WHERE type = 'earn' AND order_history_id IS NOT NULL;
