-- supabase/migrations/init_schema.sql
create extension if not exists pgcrypto;

-- Enums
DO $$ BEGIN
  CREATE TYPE app_role AS ENUM ('ADMIN','PLANCHA','FREIDORA','EMPAQUETADO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE station_type AS ENUM ('PLANCHA','FREIDORA');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE order_type AS ENUM ('DINEIN','TAKEOUT','DELIVERY');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE order_item_status AS ENUM ('EN_COLA','PENDIENTE','EN_PREPARACION','LISTO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE order_status AS ENUM (
    'RECIBIDO','EN_PROCESO','LISTO_PARA_EMPACAR','EMPACANDO','LISTO_PARA_ENTREGAR','EN_REPARTO','ENTREGADO'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE payment_status AS ENUM ('PENDIENTE','APROBADO','RECHAZADO','CANCELADO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Tablas
CREATE TABLE IF NOT EXISTS public.users (
  id bigint generated by default as identity PRIMARY KEY,
  name text NOT NULL,
  phone text,
  role app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categories (
  id bigint generated by default as identity PRIMARY KEY,
  name text NOT NULL,
  sort_order int NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.products (
  id bigint generated by default as identity PRIMARY KEY,
  category_id bigint NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
  name text NOT NULL,
  description text,
  price_cents int NOT NULL,
  station station_type NOT NULL,
  is_available boolean NOT NULL DEFAULT true,
  image_url text,
  sort_order int NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.product_modifiers (
  id bigint generated by default as identity PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  name text NOT NULL,
  price_cents int NOT NULL DEFAULT 0,
  is_required boolean NOT NULL DEFAULT false,
  max_select int NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.orders (
  id bigint generated by default as identity PRIMARY KEY,
  order_date date NOT NULL DEFAULT current_date,
  order_number int NOT NULL,
  type order_type NOT NULL,
  status order_status NOT NULL DEFAULT 'RECIBIDO',
  customer_name text,
  customer_phone text,
  address_json jsonb,
  notes text,
  subtotal_cents int NOT NULL DEFAULT 0,
  delivery_fee_cents int NOT NULL DEFAULT 0,
  total_cents int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT orders_unique_daily_number UNIQUE (order_date, order_number)
);

CREATE TABLE IF NOT EXISTS public.order_items (
  id bigint generated by default as identity PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.products(id) ON DELETE SET NULL,
  name_snapshot text NOT NULL,
  price_cents_snapshot int NOT NULL,
  qty int NOT NULL DEFAULT 1,
  station station_type NOT NULL,
  status order_item_status NOT NULL DEFAULT 'EN_COLA',
  notes text,
  group_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.payments (
  id bigint generated by default as identity PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  provider text NOT NULL,
  status payment_status NOT NULL DEFAULT 'PENDIENTE',
  external_id text,
  amount_cents int NOT NULL,
  currency text NOT NULL DEFAULT 'MXN',
  raw_json jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.loyalty_accounts (
  id bigint generated by default as identity PRIMARY KEY,
  phone text NOT NULL UNIQUE,
  name text NOT NULL,
  points_int int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.loyalty_ledger (
  id bigint generated by default as identity PRIMARY KEY,
  loyalty_account_id bigint NOT NULL REFERENCES public.loyalty_accounts(id) ON DELETE CASCADE,
  order_id bigint REFERENCES public.orders(id) ON DELETE SET NULL,
  delta_points_int int NOT NULL,
  type text NOT NULL CHECK (type IN ('earn','redeem')),
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_date ON public.orders(order_date);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_station ON public.order_items(station);
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON public.payments(order_id);

-- RPC: crear pedido con items y order_number incremental por día
CREATE OR REPLACE FUNCTION public.create_order_with_items(
  p_type order_type,
  p_customer_name text,
  p_customer_phone text,
  p_address_json jsonb,
  p_notes text,
  p_subtotal_cents int,
  p_delivery_fee_cents int,
  p_total_cents int,
  p_items jsonb
) RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
  v_order_id bigint;
  v_order_number int;
  v_order_date date := current_date;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(v_order_date::text));

  SELECT COALESCE(MAX(order_number), 0) + 1
    INTO v_order_number
    FROM public.orders
   WHERE order_date = v_order_date;

  INSERT INTO public.orders (
    order_date,
    order_number,
    type,
    status,
    customer_name,
    customer_phone,
    address_json,
    notes,
    subtotal_cents,
    delivery_fee_cents,
    total_cents
  ) VALUES (
    v_order_date,
    v_order_number,
    p_type,
    'RECIBIDO',
    p_customer_name,
    p_customer_phone,
    p_address_json,
    p_notes,
    p_subtotal_cents,
    p_delivery_fee_cents,
    p_total_cents
  ) RETURNING id INTO v_order_id;

  INSERT INTO public.order_items (
    order_id,
    product_id,
    name_snapshot,
    price_cents_snapshot,
    qty,
    station,
    status,
    notes,
    group_id
  )
  SELECT
    v_order_id,
    NULLIF(item->>'product_id', '')::bigint,
    item->>'name_snapshot',
    (item->>'price_cents_snapshot')::int,
    (item->>'qty')::int,
    (item->>'station')::station_type,
    COALESCE(NULLIF(item->>'status', '')::order_item_status, 'EN_COLA'),
    NULLIF(item->>'notes', ''),
    NULLIF(item->>'group_id', '')
  FROM jsonb_array_elements(p_items) AS item;

  RETURN v_order_id;
END;
$$;
