-- supabase/migrations/*_init_schema.sql
create extension if not exists pgcrypto;

-- Enums
do $$ begin
  create type app_role as enum ('ADMIN','PLANCHA','FREIDORA','EMPAQUETADO');
exception when duplicate_object then null; end $$;

do $$ begin
  create type station_type as enum ('PLANCHA','FREIDORA');
exception when duplicate_object then null; end $$;

do $$ begin
  create type order_type as enum ('DINEIN','TAKEOUT','DELIVERY');
exception when duplicate_object then null; end $$;

do $$ begin
  create type order_item_status as enum ('EN_COLA','PENDIENTE','EN_PREPARACION','LISTO');
exception when duplicate_object then null; end $$;

do $$ begin
  create type order_status as enum (
    'RECIBIDO','EN_PROCESO','LISTO_PARA_EMPACAR','EMPACANDO','LISTO_PARA_ENTREGAR','EN_REPARTO','ENTREGADO'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type payment_status as enum ('PENDIENTE','APROBADO','RECHAZADO','CANCELADO');
exception when duplicate_object then null; end $$;

-- Tablas
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  role app_role not null,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order int not null default 0
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict,
  name text not null,
  description text,
  price_cents int not null,
  station station_type not null,
  is_available boolean not null default true,
  image_url text,
  sort_order int not null default 0
);

create table if not exists public.product_modifiers (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  price_cents int not null default 0,
  is_required boolean not null default false,
  max_select int not null default 1
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_date date not null default current_date,
  order_number int not null,
  type order_type not null,
  status order_status not null default 'RECIBIDO',
  customer_name text,
  customer_phone text,
  address_json jsonb,
  notes text,
  subtotal_cents int not null default 0,
  delivery_fee_cents int not null default 0,
  total_cents int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_unique_daily_number unique (order_date, order_number)
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  name_snapshot text not null,
  price_cents_snapshot int not null,
  qty int not null default 1,
  station station_type not null,
  status order_item_status not null default 'EN_COLA',
  notes text,
  group_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  provider text not null,
  status payment_status not null default 'PENDIENTE',
  external_id text,
  amount_cents int not null,
  currency text not null default 'MXN',
  raw_json jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.loyalty_accounts (
  id bigint generated by default as identity primary key,
  phone text not null unique,
  name text not null,
  points_int int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.loyalty_ledger (
  id bigint generated by default as identity primary key,
  loyalty_account_id bigint not null references public.loyalty_accounts(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  delta_points_int int not null,
  type text not null check (type in ('earn','redeem')),
  note text,
  created_at timestamptz not null default now()
);

-- Seed mínimo (opcional, pero útil para arrancar)
insert into public.users (id, name, phone, role) values
  (1,'Admin','5550000000','ADMIN'),
  (2,'Plancha','5550000001','PLANCHA'),
  (3,'Freidora','5550000002','FREIDORA'),
  (4,'Empaquetado','5550000003','EMPAQUETADO')
on conflict do nothing;

insert into public.categories (id, name, sort_order) values
  (1,'Hamburguesas',1),
  (2,'Tortas',2),
  (3,'Papas',3),
  (4,'Alitas',4),
  (5,'Snacks',5)
on conflict do nothing;

insert into public.products (id, category_id, name, description, price_cents, station, is_available, sort_order) values
  (1,1,'Hamburguesa clásica','',9900,'PLANCHA',true,1),
  (2,1,'Hamburguesa doble','',12900,'PLANCHA',true,2),
  (3,2,'Torta de res','',10900,'PLANCHA',true,1),
  (4,3,'Papas','',4500,'FREIDORA',true,1),
  (5,4,'Alitas','',9900,'FREIDORA',true,1),
  (6,5,'Dedos de queso','',7900,'FREIDORA',true,1),
  (7,5,'Aros de cebolla','',6900,'FREIDORA',true,2)
on conflict do nothing;
